PROGRAM TEST_CF_TIME
USE PARKIND1, ONLY: JPIM,JPIB,JPRD
USE NETCDF
USE cmf_cf_time_mod, ONLY: cf_time_axis,cf_read_time_axis,cf_find_time_record, &
                         & cf_datetime_to_minutes,cf_calendar_matches_lleapyr
IMPLICIT NONE

CHARACTER(LEN=*), PARAMETER :: DAILY_FILE='test_cf_time_daily.nc'
CHARACTER(LEN=*), PARAMETER :: HOURLY_FILE='test_cf_time_hourly.nc'
CHARACTER(LEN=*), PARAMETER :: SECONDS_FILE='test_cf_time_seconds.nc'
CHARACTER(LEN=*), PARAMETER :: MINUTES_FILE='test_cf_time_minutes.nc'
CHARACTER(LEN=*), PARAMETER :: GAP_FILE='test_cf_time_gap.nc'
CHARACTER(LEN=*), PARAMETER :: UNSUPPORTED_FILE='test_cf_time_unsupported.nc'
CHARACTER(LEN=*), PARAMETER :: TIMEZONE_FILE='test_cf_time_timezone.nc'
CHARACTER(LEN=*), PARAMETER :: VARIABLE_BOUNDS_FILE='test_cf_time_variable_bounds.nc'
INTEGER(KIND=JPIM) :: NFAIL

NFAIL=0
IF ( COMMAND_ARGUMENT_COUNT()==5 ) THEN
  CALL TEST_EXTERNAL_FILE(NFAIL)
  IF ( NFAIL/=0 ) ERROR STOP 1
  WRITE(*,'(A)') '[ALL TESTS PASSED] external CF time file'
  STOP
ENDIF
CALL CREATE_DAILY_FILE(DAILY_FILE)
CALL CREATE_HOURLY_FILE(HOURLY_FILE)
CALL CREATE_SIMPLE_FILE(SECONDS_FILE,'seconds since 2000-01-01 00:00:00','standard', &
                       & (/0._JPRD,180._JPRD,360._JPRD/))
CALL CREATE_SIMPLE_FILE(MINUTES_FILE,'minutes since 2000-01-01 00:00:00','standard', &
                       & (/0._JPRD,90._JPRD,180._JPRD/))
CALL CREATE_SIMPLE_FILE(GAP_FILE,'hours since 2000-01-01 00:00:00','standard', &
                       & (/0._JPRD,1._JPRD,3._JPRD/))
CALL CREATE_SIMPLE_FILE(UNSUPPORTED_FILE,'hours since 2000-01-01 00:00:00','360_day', &
                       & (/0._JPRD,1._JPRD,2._JPRD/))
CALL CREATE_SIMPLE_FILE(TIMEZONE_FILE,'hours since 2000-01-01 00:00 +01:00','standard', &
                       & (/0._JPRD,1._JPRD,2._JPRD/))
CALL CREATE_VARIABLE_BOUNDS_FILE(VARIABLE_BOUNDS_FILE)
CALL TEST_DAILY_BOUNDS(DAILY_FILE,NFAIL)
CALL TEST_HOURLY_RECORD(HOURLY_FILE,NFAIL)
CALL TEST_UNIT_INTERVAL(SECONDS_FILE,3_JPIB,'seconds units',NFAIL)
CALL TEST_UNIT_INTERVAL(MINUTES_FILE,90_JPIB,'minutes units',NFAIL)
CALL TEST_REJECTED_AXIS(GAP_FILE,'time gap',NFAIL)
CALL TEST_REJECTED_AXIS(UNSUPPORTED_FILE,'unsupported calendar',NFAIL)
CALL TEST_TIMEZONE(TIMEZONE_FILE,NFAIL)
CALL TEST_REJECTED_AXIS(VARIABLE_BOUNDS_FILE,'variable time-bounds width',NFAIL)
CALL TEST_CALENDARS(NFAIL)
CALL DELETE_FILE(DAILY_FILE)
CALL DELETE_FILE(HOURLY_FILE)
CALL DELETE_FILE(SECONDS_FILE)
CALL DELETE_FILE(MINUTES_FILE)
CALL DELETE_FILE(GAP_FILE)
CALL DELETE_FILE(UNSUPPORTED_FILE)
CALL DELETE_FILE(TIMEZONE_FILE)
CALL DELETE_FILE(VARIABLE_BOUNDS_FILE)

IF ( NFAIL/=0 ) THEN
  WRITE(*,'(A,I0)') '[TEST FAILED] test_cf_time: ',NFAIL
  ERROR STOP 1
ENDIF
WRITE(*,'(A)') '[ALL TESTS PASSED] test_cf_time'

CONTAINS

SUBROUTINE CHECK_NC(STATUS,LABEL)
INTEGER, INTENT(IN) :: STATUS
CHARACTER(LEN=*), INTENT(IN) :: LABEL
IF ( STATUS==NF90_NOERR ) RETURN
WRITE(*,'(3A)') '[NetCDF ERROR] ',TRIM(LABEL),': '//TRIM(NF90_STRERROR(STATUS))
ERROR STOP 1
END SUBROUTINE CHECK_NC

SUBROUTINE ASSERT_TRUE(CONDITION,LABEL,NFAIL)
LOGICAL, INTENT(IN) :: CONDITION
CHARACTER(LEN=*), INTENT(IN) :: LABEL
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
IF ( CONDITION ) RETURN
NFAIL=NFAIL+1
WRITE(*,'(2A)') '[FAIL] ',TRIM(LABEL)
END SUBROUTINE ASSERT_TRUE

SUBROUTINE ASSERT_INT(ACTUAL,EXPECTED,LABEL,NFAIL)
INTEGER(KIND=JPIM), INTENT(IN) :: ACTUAL,EXPECTED
CHARACTER(LEN=*), INTENT(IN) :: LABEL
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
IF ( ACTUAL==EXPECTED ) RETURN
NFAIL=NFAIL+1
WRITE(*,'(2A)') '[FAIL] ',TRIM(LABEL)
WRITE(*,'(A,I0,A,I0)') '  actual=',ACTUAL,' expected=',EXPECTED
END SUBROUTINE ASSERT_INT

SUBROUTINE CREATE_DAILY_FILE(PATH)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER :: NCID,TIME_DIMID,BOUND_DIMID,TIME_VARID,BOUND_VARID
REAL(KIND=JPRD) :: TIME(3),BOUNDS(2,3)

TIME=(/0.5_JPRD,1.5_JPRD,2.5_JPRD/)
BOUNDS(:,1)=(/0._JPRD,1._JPRD/)
BOUNDS(:,2)=(/1._JPRD,2._JPRD/)
BOUNDS(:,3)=(/2._JPRD,3._JPRD/)
CALL CHECK_NC(NF90_CREATE(PATH,NF90_CLOBBER,NCID),'create daily fixture')
CALL CHECK_NC(NF90_DEF_DIM(NCID,'time',3,TIME_DIMID),'define time dimension')
CALL CHECK_NC(NF90_DEF_DIM(NCID,'bnds',2,BOUND_DIMID),'define bounds dimension')
CALL CHECK_NC(NF90_DEF_VAR(NCID,'time',NF90_DOUBLE,(/TIME_DIMID/),TIME_VARID),'define time variable')
CALL CHECK_NC(NF90_DEF_VAR(NCID,'time_bounds',NF90_DOUBLE,(/BOUND_DIMID,TIME_DIMID/),BOUND_VARID),'define bounds variable')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'units','days since 1850-01-01 00:00:00'),'write units')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'calendar','gregorian'),'write calendar')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'bounds','time_bounds'),'write bounds attribute')
CALL CHECK_NC(NF90_ENDDEF(NCID),'end definition')
CALL CHECK_NC(NF90_PUT_VAR(NCID,TIME_VARID,TIME),'write time')
CALL CHECK_NC(NF90_PUT_VAR(NCID,BOUND_VARID,BOUNDS),'write bounds')
CALL CHECK_NC(NF90_CLOSE(NCID),'close daily fixture')
END SUBROUTINE CREATE_DAILY_FILE

SUBROUTINE CREATE_HOURLY_FILE(PATH)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER :: NCID,TIME_DIMID,TIME_VARID
REAL(KIND=JPRD) :: TIME(3)

TIME=(/0._JPRD,3._JPRD,6._JPRD/)
CALL CHECK_NC(NF90_CREATE(PATH,NF90_CLOBBER,NCID),'create hourly fixture')
CALL CHECK_NC(NF90_DEF_DIM(NCID,'time',3,TIME_DIMID),'define time dimension')
CALL CHECK_NC(NF90_DEF_VAR(NCID,'time',NF90_DOUBLE,(/TIME_DIMID/),TIME_VARID),'define time variable')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'units','hours since 1999-12-31 21:00:00'),'write units')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'calendar','proleptic_gregorian'),'write calendar')
CALL CHECK_NC(NF90_ENDDEF(NCID),'end definition')
CALL CHECK_NC(NF90_PUT_VAR(NCID,TIME_VARID,TIME),'write time')
CALL CHECK_NC(NF90_CLOSE(NCID),'close hourly fixture')
END SUBROUTINE CREATE_HOURLY_FILE

SUBROUTINE CREATE_SIMPLE_FILE(PATH,UNITS,CALENDAR,TIME)
CHARACTER(LEN=*), INTENT(IN) :: PATH,UNITS,CALENDAR
REAL(KIND=JPRD), INTENT(IN) :: TIME(:)
INTEGER :: NCID,TIME_DIMID,TIME_VARID

CALL CHECK_NC(NF90_CREATE(PATH,NF90_CLOBBER,NCID),'create simple fixture')
CALL CHECK_NC(NF90_DEF_DIM(NCID,'time',SIZE(TIME),TIME_DIMID),'define simple time dimension')
CALL CHECK_NC(NF90_DEF_VAR(NCID,'time',NF90_DOUBLE,(/TIME_DIMID/),TIME_VARID),'define simple time variable')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'units',UNITS),'write simple units')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'calendar',CALENDAR),'write simple calendar')
CALL CHECK_NC(NF90_ENDDEF(NCID),'end simple definition')
CALL CHECK_NC(NF90_PUT_VAR(NCID,TIME_VARID,TIME),'write simple time')
CALL CHECK_NC(NF90_CLOSE(NCID),'close simple fixture')
END SUBROUTINE CREATE_SIMPLE_FILE

SUBROUTINE CREATE_VARIABLE_BOUNDS_FILE(PATH)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER :: NCID,TIME_DIMID,BOUND_DIMID,TIME_VARID,BOUND_VARID
REAL(KIND=JPRD) :: TIME(3),BOUNDS(2,3)

TIME=(/5._JPRD,15._JPRD,25._JPRD/)
BOUNDS(:,1)=(/0._JPRD,8._JPRD/)
BOUNDS(:,2)=(/8._JPRD,22._JPRD/)
BOUNDS(:,3)=(/22._JPRD,30._JPRD/)
CALL CHECK_NC(NF90_CREATE(PATH,NF90_CLOBBER,NCID),'create variable-bounds fixture')
CALL CHECK_NC(NF90_DEF_DIM(NCID,'time',3,TIME_DIMID),'define variable-bounds time dimension')
CALL CHECK_NC(NF90_DEF_DIM(NCID,'bnds',2,BOUND_DIMID),'define variable-bounds dimension')
CALL CHECK_NC(NF90_DEF_VAR(NCID,'time',NF90_DOUBLE,(/TIME_DIMID/),TIME_VARID),'define variable-bounds time')
CALL CHECK_NC(NF90_DEF_VAR(NCID,'time_bounds',NF90_DOUBLE,(/BOUND_DIMID,TIME_DIMID/),BOUND_VARID), &
             &'define variable bounds')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'units','hours since 2000-01-01 00:00:00'),'write bounds units')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'calendar','standard'),'write bounds calendar')
CALL CHECK_NC(NF90_PUT_ATT(NCID,TIME_VARID,'bounds','time_bounds'),'write bounds attribute')
CALL CHECK_NC(NF90_ENDDEF(NCID),'end variable-bounds definition')
CALL CHECK_NC(NF90_PUT_VAR(NCID,TIME_VARID,TIME),'write variable-bounds time')
CALL CHECK_NC(NF90_PUT_VAR(NCID,BOUND_VARID,BOUNDS),'write variable bounds')
CALL CHECK_NC(NF90_CLOSE(NCID),'close variable-bounds fixture')
END SUBROUTINE CREATE_VARIABLE_BOUNDS_FILE

SUBROUTINE TEST_DAILY_BOUNDS(PATH,NFAIL)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
TYPE(cf_time_axis) :: AXIS
INTEGER :: NCID
INTEGER(KIND=JPIM) :: IERR,RECORD
CHARACTER(LEN=256) :: MESSAGE

CALL CHECK_NC(NF90_OPEN(PATH,NF90_NOWRITE,NCID),'open daily fixture')
CALL cf_read_time_axis(NCID,'time',AXIS,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'read daily CF time: '//TRIM(MESSAGE),NFAIL)
CALL ASSERT_TRUE(AXIS%HAS_BOUNDS,'daily time bounds detected',NFAIL)
CALL ASSERT_TRUE(AXIS%DT_MINUTES==1440_JPIB,'daily interval is 1440 minutes',NFAIL)
CALL cf_find_time_record(AXIS,18500101_JPIM,0_JPIM,0_JPIM,RECORD,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'find first daily record: '//TRIM(MESSAGE),NFAIL)
CALL ASSERT_INT(RECORD,1_JPIM,'00:00 is contained by noon-centered record 1',NFAIL)
CALL cf_find_time_record(AXIS,18500102_JPIM,0_JPIM,0_JPIM,RECORD,IERR,MESSAGE)
CALL ASSERT_INT(RECORD,2_JPIM,'next midnight selects record 2',NFAIL)
CALL cf_find_time_record(AXIS,18500101_JPIM,6_JPIM,0_JPIM,RECORD,IERR,MESSAGE,.TRUE.)
CALL ASSERT_TRUE(IERR/=0_JPIM,'reader mode rejects a start inside time bounds',NFAIL)
CALL CHECK_NC(NF90_CLOSE(NCID),'close daily fixture')
END SUBROUTINE TEST_DAILY_BOUNDS

SUBROUTINE TEST_HOURLY_RECORD(PATH,NFAIL)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
TYPE(cf_time_axis) :: AXIS
INTEGER :: NCID
INTEGER(KIND=JPIM) :: IERR,RECORD
CHARACTER(LEN=256) :: MESSAGE

CALL CHECK_NC(NF90_OPEN(PATH,NF90_NOWRITE,NCID),'open hourly fixture')
CALL cf_read_time_axis(NCID,'time',AXIS,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'read hourly CF time: '//TRIM(MESSAGE),NFAIL)
CALL ASSERT_TRUE(.NOT.AXIS%HAS_BOUNDS,'hourly fixture has no bounds',NFAIL)
CALL ASSERT_TRUE(AXIS%DT_MINUTES==180_JPIB,'hourly interval is 180 minutes',NFAIL)
CALL cf_find_time_record(AXIS,20000101_JPIM,0_JPIM,0_JPIM,RECORD,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'find 2000-01-01 00:00: '//TRIM(MESSAGE),NFAIL)
CALL ASSERT_INT(RECORD,2_JPIM,'1999-12-31 21:00 file selects record 2',NFAIL)
CALL cf_find_time_record(AXIS,19991231_JPIM,22_JPIM,0_JPIM,RECORD,IERR,MESSAGE)
CALL ASSERT_TRUE(IERR/=0_JPIM,'no-bounds axis rejects a non-matching time',NFAIL)
CALL CHECK_NC(NF90_CLOSE(NCID),'close hourly fixture')
END SUBROUTINE TEST_HOURLY_RECORD

SUBROUTINE TEST_UNIT_INTERVAL(PATH,EXPECTED_MINUTES,LABEL,NFAIL)
CHARACTER(LEN=*), INTENT(IN) :: PATH,LABEL
INTEGER(KIND=JPIB), INTENT(IN) :: EXPECTED_MINUTES
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
TYPE(cf_time_axis) :: AXIS
INTEGER :: NCID
INTEGER(KIND=JPIM) :: IERR
CHARACTER(LEN=256) :: MESSAGE

CALL CHECK_NC(NF90_OPEN(PATH,NF90_NOWRITE,NCID),'open unit fixture')
CALL cf_read_time_axis(NCID,'time',AXIS,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'read '//TRIM(LABEL)//': '//TRIM(MESSAGE),NFAIL)
IF ( IERR==0_JPIM ) CALL ASSERT_TRUE(AXIS%DT_MINUTES==EXPECTED_MINUTES,TRIM(LABEL)//' interval',NFAIL)
CALL CHECK_NC(NF90_CLOSE(NCID),'close unit fixture')
END SUBROUTINE TEST_UNIT_INTERVAL

SUBROUTINE TEST_REJECTED_AXIS(PATH,LABEL,NFAIL)
CHARACTER(LEN=*), INTENT(IN) :: PATH,LABEL
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
TYPE(cf_time_axis) :: AXIS
INTEGER :: NCID
INTEGER(KIND=JPIM) :: IERR
CHARACTER(LEN=256) :: MESSAGE

CALL CHECK_NC(NF90_OPEN(PATH,NF90_NOWRITE,NCID),'open rejected fixture')
CALL cf_read_time_axis(NCID,'time',AXIS,IERR,MESSAGE)
CALL ASSERT_TRUE(IERR/=0_JPIM,TRIM(LABEL)//' is rejected',NFAIL)
CALL CHECK_NC(NF90_CLOSE(NCID),'close rejected fixture')
END SUBROUTINE TEST_REJECTED_AXIS

SUBROUTINE TEST_TIMEZONE(PATH,NFAIL)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
TYPE(cf_time_axis) :: AXIS
INTEGER :: NCID
INTEGER(KIND=JPIM) :: IERR,RECORD
CHARACTER(LEN=256) :: MESSAGE

CALL CHECK_NC(NF90_OPEN(PATH,NF90_NOWRITE,NCID),'open timezone fixture')
CALL cf_read_time_axis(NCID,'time',AXIS,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'read timezone CF time: '//TRIM(MESSAGE),NFAIL)
CALL cf_find_time_record(AXIS,20000101_JPIM,0_JPIM,0_JPIM,RECORD,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'find timezone-adjusted record: '//TRIM(MESSAGE),NFAIL)
CALL ASSERT_INT(RECORD,2_JPIM,'+01:00 reference is converted to UTC',NFAIL)
CALL CHECK_NC(NF90_CLOSE(NCID),'close timezone fixture')
END SUBROUTINE TEST_TIMEZONE

SUBROUTINE TEST_CALENDARS(NFAIL)
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
INTEGER(KIND=JPIB) :: GREG_MARCH,NOLEAP_MARCH,GREG_JAN,NOLEAP_JAN
INTEGER(KIND=JPIM) :: IERR
CHARACTER(LEN=256) :: MESSAGE
LOGICAL :: MATCHES

CALL cf_datetime_to_minutes('gregorian',20000101_JPIM,0_JPIM,0_JPIM,GREG_JAN,IERR,MESSAGE)
CALL cf_datetime_to_minutes('gregorian',20000301_JPIM,0_JPIM,0_JPIM,GREG_MARCH,IERR,MESSAGE)
CALL ASSERT_TRUE(GREG_MARCH-GREG_JAN==60_JPIB*1440_JPIB,'Gregorian 2000 includes February 29',NFAIL)
CALL cf_datetime_to_minutes('365_day',20000101_JPIM,0_JPIM,0_JPIM,NOLEAP_JAN,IERR,MESSAGE)
CALL cf_datetime_to_minutes('365_day',20000301_JPIM,0_JPIM,0_JPIM,NOLEAP_MARCH,IERR,MESSAGE)
CALL ASSERT_TRUE(NOLEAP_MARCH-NOLEAP_JAN==59_JPIB*1440_JPIB,'365_day excludes February 29',NFAIL)
MATCHES=cf_calendar_matches_lleapyr('365_day',.FALSE.,IERR,MESSAGE)
CALL ASSERT_TRUE(MATCHES,'365_day matches LLEAPYR=.FALSE.',NFAIL)
MATCHES=cf_calendar_matches_lleapyr('gregorian',.TRUE.,IERR,MESSAGE)
CALL ASSERT_TRUE(MATCHES,'gregorian matches LLEAPYR=.TRUE.',NFAIL)
MATCHES=cf_calendar_matches_lleapyr('gregorian',.FALSE.,IERR,MESSAGE)
CALL ASSERT_TRUE(.NOT.MATCHES,'gregorian rejects LLEAPYR=.FALSE.',NFAIL)
END SUBROUTINE TEST_CALENDARS

SUBROUTINE TEST_EXTERNAL_FILE(NFAIL)
INTEGER(KIND=JPIM), INTENT(INOUT) :: NFAIL
TYPE(cf_time_axis) :: AXIS
CHARACTER(LEN=1024) :: PATH
CHARACTER(LEN=64) :: TIME_NAME
CHARACTER(LEN=32) :: ARG
CHARACTER(LEN=256) :: MESSAGE
INTEGER :: NCID,IOS
INTEGER(KIND=JPIM) :: YYYYMMDD,HOUR,EXPECTED_RECORD,RECORD,IERR

CALL GET_COMMAND_ARGUMENT(1,PATH)
CALL GET_COMMAND_ARGUMENT(2,TIME_NAME)
CALL GET_COMMAND_ARGUMENT(3,ARG)
READ(ARG,*,IOSTAT=IOS) YYYYMMDD
IF ( IOS/=0 ) ERROR STOP 'invalid YYYYMMDD argument'
CALL GET_COMMAND_ARGUMENT(4,ARG)
READ(ARG,*,IOSTAT=IOS) HOUR
IF ( IOS/=0 ) ERROR STOP 'invalid hour argument'
CALL GET_COMMAND_ARGUMENT(5,ARG)
READ(ARG,*,IOSTAT=IOS) EXPECTED_RECORD
IF ( IOS/=0 ) ERROR STOP 'invalid expected-record argument'

CALL CHECK_NC(NF90_OPEN(TRIM(PATH),NF90_NOWRITE,NCID),'open external CF file')
CALL cf_read_time_axis(NCID,TRIM(TIME_NAME),AXIS,IERR,MESSAGE)
CALL ASSERT_INT(IERR,0_JPIM,'read external CF time: '//TRIM(MESSAGE),NFAIL)
IF ( IERR==0_JPIM ) THEN
  CALL cf_find_time_record(AXIS,YYYYMMDD,HOUR,0_JPIM,RECORD,IERR,MESSAGE,.TRUE.)
  CALL ASSERT_INT(IERR,0_JPIM,'select external CF record: '//TRIM(MESSAGE),NFAIL)
  CALL ASSERT_INT(RECORD,EXPECTED_RECORD,'external CF record number',NFAIL)
  WRITE(*,'(2A)') '  units: ',TRIM(AXIS%UNITS)
  WRITE(*,'(2A)') '  calendar: ',TRIM(AXIS%CALENDAR)
  WRITE(*,'(A,I0)') '  interval [min]: ',AXIS%DT_MINUTES
  WRITE(*,'(A,I0)') '  selected record: ',RECORD
ENDIF
CALL CHECK_NC(NF90_CLOSE(NCID),'close external CF file')
END SUBROUTINE TEST_EXTERNAL_FILE

SUBROUTINE DELETE_FILE(PATH)
CHARACTER(LEN=*), INTENT(IN) :: PATH
INTEGER :: NCID,STATUS
STATUS=NF90_OPEN(PATH,NF90_WRITE,NCID)
IF ( STATUS==NF90_NOERR ) STATUS=NF90_CLOSE(NCID)
CALL EXECUTE_COMMAND_LINE('/bin/rm -f '//TRIM(PATH))
END SUBROUTINE DELETE_FILE

END PROGRAM TEST_CF_TIME
