MODULE CMF_CF_TIME_MOD
!==========================================================
!* PURPOSE: Read and validate CF-compliant NetCDF time axes.
!*
!* The top-level Makefile compiles this source directly so the legacy
!* reader can share it with src/common + src/io without making the
!* optional libcommon archive mandatory for a standard build.
!==========================================================
USE PARKIND1, ONLY: JPIM, JPIB, JPRD
#ifdef UseCDF_CMF
USE NETCDF
#endif
IMPLICIT NONE
PRIVATE

INTEGER, PARAMETER :: CF_STRLEN = 256
INTEGER, PARAMETER :: CAL_GREGORIAN = 1
INTEGER, PARAMETER :: CAL_NOLEAP = 2

TYPE, PUBLIC :: CF_TIME_AXIS
  INTEGER(KIND=JPIM) :: NTIME = 0
  INTEGER(KIND=JPIB) :: DT_MINUTES = 0_JPIB
  LOGICAL :: HAS_BOUNDS = .FALSE.
  CHARACTER(LEN=CF_STRLEN) :: UNITS = ''
  CHARACTER(LEN=32) :: CALENDAR = ''
  INTEGER(KIND=JPIB), ALLOCATABLE :: CENTER_MINUTES(:)
  INTEGER(KIND=JPIB), ALLOCATABLE :: LOWER_MINUTES(:)
  INTEGER(KIND=JPIB), ALLOCATABLE :: UPPER_MINUTES(:)
END TYPE CF_TIME_AXIS

PUBLIC :: CF_DATETIME_TO_MINUTES
PUBLIC :: CF_FIND_TIME_RECORD
PUBLIC :: CF_CALENDAR_MATCHES_LLEAPYR
PUBLIC :: CF_CALENDAR_USES_LEAP_DAY
#ifdef UseCDF_CMF
PUBLIC :: CF_READ_TIME_AXIS
PUBLIC :: CF_RESOLVE_TIME_RECORD
#endif

CONTAINS

!####################################################################
PURE FUNCTION LOWERCASE(TEXT) RESULT(LOWER)
CHARACTER(LEN=*), INTENT(IN) :: TEXT
CHARACTER(LEN=LEN(TEXT)) :: LOWER
INTEGER :: I, CODE

LOWER=TEXT
DO I=1,LEN(TEXT)
  CODE=IACHAR(TEXT(I:I))
  IF ( CODE>=IACHAR('A') .AND. CODE<=IACHAR('Z') ) LOWER(I:I)=ACHAR(CODE+32)
ENDDO
END FUNCTION LOWERCASE
!####################################################################

!####################################################################
PURE FUNCTION SANITIZE_STRING(TEXT) RESULT(CLEAN)
CHARACTER(LEN=*), INTENT(IN) :: TEXT
CHARACTER(LEN=LEN(TEXT)) :: CLEAN
INTEGER :: I

CLEAN=TEXT
DO I=1,LEN(TEXT)
  IF ( IACHAR(CLEAN(I:I))==0 ) CLEAN(I:I)=' '
ENDDO
END FUNCTION SANITIZE_STRING
!####################################################################

!####################################################################
SUBROUTINE SET_ERROR(IERR,MESSAGE,TEXT)
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
CHARACTER(LEN=*), INTENT(IN) :: TEXT

IERR=1
MESSAGE=TRIM(TEXT)
END SUBROUTINE SET_ERROR
!####################################################################

!####################################################################
SUBROUTINE NORMALIZE_CALENDAR(CALENDAR,ICAL,NORMALIZED,IERR,MESSAGE)
CHARACTER(LEN=*), INTENT(IN) :: CALENDAR
INTEGER, INTENT(OUT) :: ICAL
CHARACTER(LEN=*), INTENT(OUT) :: NORMALIZED
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
CHARACTER(LEN=32) :: CAL

IERR=0
MESSAGE=''
ICAL=0
NORMALIZED=''
CAL=TRIM(LOWERCASE(ADJUSTL(SANITIZE_STRING(CALENDAR))))
IF ( LEN_TRIM(CAL)==0 ) CAL='standard'

SELECT CASE (TRIM(CAL))
CASE ('gregorian','standard','proleptic_gregorian')
  ICAL=CAL_GREGORIAN
  NORMALIZED=TRIM(CAL)
CASE ('365_day','noleap')
  ICAL=CAL_NOLEAP
  NORMALIZED=TRIM(CAL)
CASE DEFAULT
  CALL SET_ERROR(IERR,MESSAGE,'unsupported CF calendar: '//TRIM(CAL))
END SELECT
END SUBROUTINE NORMALIZE_CALENDAR
!####################################################################

!####################################################################
PURE LOGICAL FUNCTION IS_GREGORIAN_LEAP_YEAR(YEAR)
INTEGER(KIND=JPIM), INTENT(IN) :: YEAR

IS_GREGORIAN_LEAP_YEAR = MOD(YEAR,400_JPIM)==0_JPIM .OR. &
                       &(MOD(YEAR,4_JPIM)==0_JPIM .AND. MOD(YEAR,100_JPIM)/=0_JPIM)
END FUNCTION IS_GREGORIAN_LEAP_YEAR
!####################################################################

!####################################################################
SUBROUTINE DATE_PARTS_TO_MINUTES(YEAR,MONTH,DAY,HOUR,MINUTE,ICAL,VALUE,IERR,MESSAGE)
INTEGER(KIND=JPIM), INTENT(IN) :: YEAR,MONTH,DAY,HOUR,MINUTE
INTEGER, INTENT(IN) :: ICAL
INTEGER(KIND=JPIB), INTENT(OUT) :: VALUE
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
INTEGER(KIND=JPIM) :: MONTH_DAYS(12), IMON
INTEGER(KIND=JPIB) :: DAYS

IERR=0
MESSAGE=''
VALUE=0_JPIB
IF ( YEAR<1 .OR. MONTH<1 .OR. MONTH>12 .OR. HOUR<0 .OR. HOUR>23 .OR. MINUTE<0 .OR. MINUTE>59 ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'invalid datetime component in CF time metadata')
  RETURN
ENDIF

MONTH_DAYS=(/31,28,31,30,31,30,31,31,30,31,30,31/)
IF ( ICAL==CAL_GREGORIAN .AND. IS_GREGORIAN_LEAP_YEAR(YEAR) ) MONTH_DAYS(2)=29
IF ( DAY<1 .OR. DAY>MONTH_DAYS(MONTH) ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'invalid day for CF calendar')
  RETURN
ENDIF

IF ( ICAL==CAL_NOLEAP ) THEN
  DAYS=INT(YEAR-1,KIND=JPIB)*365_JPIB
ELSE
  DAYS=INT(YEAR-1,KIND=JPIB)*365_JPIB + INT((YEAR-1)/4,KIND=JPIB) &
      &-INT((YEAR-1)/100,KIND=JPIB)+INT((YEAR-1)/400,KIND=JPIB)
ENDIF
DO IMON=1,MONTH-1
  DAYS=DAYS+INT(MONTH_DAYS(IMON),KIND=JPIB)
ENDDO
DAYS=DAYS+INT(DAY-1,KIND=JPIB)
VALUE=(DAYS*24_JPIB+INT(HOUR,KIND=JPIB))*60_JPIB+INT(MINUTE,KIND=JPIB)
END SUBROUTINE DATE_PARTS_TO_MINUTES
!####################################################################

!####################################################################
SUBROUTINE CF_DATETIME_TO_MINUTES(CALENDAR,YYYYMMDD,HOUR,MINUTE,VALUE,IERR,MESSAGE)
CHARACTER(LEN=*), INTENT(IN) :: CALENDAR
INTEGER(KIND=JPIM), INTENT(IN) :: YYYYMMDD,HOUR,MINUTE
INTEGER(KIND=JPIB), INTENT(OUT) :: VALUE
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
INTEGER :: ICAL
INTEGER(KIND=JPIM) :: YEAR,MONTH,DAY
CHARACTER(LEN=32) :: NORMALIZED

ICAL=0
CALL NORMALIZE_CALENDAR(CALENDAR,ICAL,NORMALIZED,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN
YEAR=YYYYMMDD/10000_JPIM
MONTH=MOD(YYYYMMDD/100_JPIM,100_JPIM)
DAY=MOD(YYYYMMDD,100_JPIM)
CALL DATE_PARTS_TO_MINUTES(YEAR,MONTH,DAY,HOUR,MINUTE,ICAL,VALUE,IERR,MESSAGE)
END SUBROUTINE CF_DATETIME_TO_MINUTES
!####################################################################

#ifdef UseCDF_CMF
!####################################################################
SUBROUTINE PARSE_REFERENCE_DATETIME(TEXT,ICAL,REFERENCE_MINUTES,IERR,MESSAGE)
CHARACTER(LEN=*), INTENT(IN) :: TEXT
INTEGER, INTENT(IN) :: ICAL
INTEGER(KIND=JPIB), INTENT(OUT) :: REFERENCE_MINUTES
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
CHARACTER(LEN=CF_STRLEN) :: REF,TIMEZONE,TZCOMPACT
INTEGER(KIND=JPIM) :: YEAR,MONTH,DAY,HOUR,MINUTE,SECOND,TZHOUR,TZMINUTE,TZOFFSET
INTEGER :: IOS, N, I, J, TZSIGN, TZSTART

IERR=0
MESSAGE=''
REFERENCE_MINUTES=0_JPIB
REF=ADJUSTL(TEXT)
N=LEN_TRIM(REF)
TIMEZONE=''
TZSTART=0
DO I=11,N
  IF ( REF(I:I)=='+' .OR. REF(I:I)=='-' ) THEN
    TZSTART=I
    EXIT
  ENDIF
ENDDO
IF ( TZSTART==0 .AND. N>=1 ) THEN
  IF ( REF(N:N)=='Z' .OR. REF(N:N)=='z' ) TZSTART=N
ENDIF
IF ( TZSTART==0 .AND. N>=3 ) THEN
  IF ( LOWERCASE(REF(N-2:N))=='utc' ) TZSTART=N-2
ENDIF
IF ( TZSTART>0 ) THEN
  TIMEZONE=TRIM(ADJUSTL(REF(TZSTART:N)))
  REF(TZSTART:N)=' '
  N=LEN_TRIM(REF)
ENDIF
IF ( N<10 ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'invalid reference datetime in CF time units: '//TRIM(REF))
  RETURN
ENDIF
IF ( REF(5:5)/='-' .OR. REF(8:8)/='-' ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'CF reference date must use YYYY-MM-DD: '//TRIM(REF))
  RETURN
ENDIF

READ(REF(1:4),'(I4)',IOSTAT=IOS) YEAR
IF ( IOS/=0 ) GOTO 900
READ(REF(6:7),'(I2)',IOSTAT=IOS) MONTH
IF ( IOS/=0 ) GOTO 900
READ(REF(9:10),'(I2)',IOSTAT=IOS) DAY
IF ( IOS/=0 ) GOTO 900
HOUR=0
MINUTE=0
SECOND=0
IF ( N>=13 ) THEN
  IF ( REF(11:11)=='T' .OR. REF(11:11)=='t' ) REF(11:11)=' '
  IF ( REF(11:11)/=' ' ) GOTO 900
  READ(REF(12:13),'(I2)',IOSTAT=IOS) HOUR
  IF ( IOS/=0 ) GOTO 900
ENDIF
IF ( N>=16 ) THEN
  IF ( REF(14:14)/=':' ) GOTO 900
  READ(REF(15:16),'(I2)',IOSTAT=IOS) MINUTE
  IF ( IOS/=0 ) GOTO 900
ENDIF
IF ( N>=19 ) THEN
  IF ( REF(17:17)/=':' ) GOTO 900
  READ(REF(18:19),'(I2)',IOSTAT=IOS) SECOND
  IF ( IOS/=0 ) GOTO 900
ENDIF
IF ( N/=10 .AND. N/=13 .AND. N/=16 .AND. N/=19 ) GOTO 900
IF ( SECOND/=0 ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'CF reference time must align to a whole minute: '//TRIM(REF))
  RETURN
ENDIF
CALL DATE_PARTS_TO_MINUTES(YEAR,MONTH,DAY,HOUR,MINUTE,ICAL,REFERENCE_MINUTES,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN

! CF reference datetimes may include a time-zone suffix. Convert the
! local reference time to UTC: UTC = local time - UTC offset.
TZOFFSET=0_JPIM
IF ( LEN_TRIM(TIMEZONE)>0 ) THEN
  IF ( TRIM(LOWERCASE(TIMEZONE))/='z' .AND. TRIM(LOWERCASE(TIMEZONE))/='utc' ) THEN
    IF ( TIMEZONE(1:1)=='+' ) THEN
      TZSIGN=1
    ELSEIF ( TIMEZONE(1:1)=='-' ) THEN
      TZSIGN=-1
    ELSE
      CALL SET_ERROR(IERR,MESSAGE,'unsupported CF reference-time timezone: '//TRIM(TIMEZONE))
      RETURN
    ENDIF
    TZCOMPACT=''
    J=0
    DO I=2,LEN_TRIM(TIMEZONE)
      IF ( TIMEZONE(I:I)==':' ) CYCLE
      J=J+1
      TZCOMPACT(J:J)=TIMEZONE(I:I)
    ENDDO
    IF ( J/=2 .AND. J/=4 ) THEN
      CALL SET_ERROR(IERR,MESSAGE,'CF timezone must be Z, UTC, +/-HH, +/-HHMM, or +/-HH:MM')
      RETURN
    ENDIF
    READ(TZCOMPACT(1:2),'(I2)',IOSTAT=IOS) TZHOUR
    IF ( IOS/=0 ) GOTO 910
    TZMINUTE=0_JPIM
    IF ( J==4 ) THEN
      READ(TZCOMPACT(3:4),'(I2)',IOSTAT=IOS) TZMINUTE
      IF ( IOS/=0 ) GOTO 910
    ENDIF
    IF ( TZHOUR>23 .OR. TZMINUTE>59 ) GOTO 910
    TZOFFSET=TZSIGN*(TZHOUR*60_JPIM+TZMINUTE)
  ENDIF
ENDIF
REFERENCE_MINUTES=REFERENCE_MINUTES-INT(TZOFFSET,KIND=JPIB)
RETURN

900 CONTINUE
CALL SET_ERROR(IERR,MESSAGE,'cannot parse reference datetime in CF time units: '//TRIM(REF))
RETURN
910 CONTINUE
CALL SET_ERROR(IERR,MESSAGE,'invalid CF reference-time timezone: '//TRIM(TIMEZONE))
END SUBROUTINE PARSE_REFERENCE_DATETIME
!####################################################################

!####################################################################
SUBROUTINE PARSE_CF_UNITS(UNITS,CALENDAR,UNIT_MINUTES,REFERENCE_MINUTES,NORMALIZED_CALENDAR,IERR,MESSAGE)
CHARACTER(LEN=*), INTENT(IN) :: UNITS,CALENDAR
REAL(KIND=JPRD), INTENT(OUT) :: UNIT_MINUTES
INTEGER(KIND=JPIB), INTENT(OUT) :: REFERENCE_MINUTES
CHARACTER(LEN=*), INTENT(OUT) :: NORMALIZED_CALENDAR
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
CHARACTER(LEN=CF_STRLEN) :: LOWER_UNITS, UNIT_NAME, REFERENCE_TEXT
INTEGER :: ISINCE,ICAL

IERR=0
MESSAGE=''
LOWER_UNITS=TRIM(LOWERCASE(ADJUSTL(SANITIZE_STRING(UNITS))))
ISINCE=INDEX(LOWER_UNITS,' since ')
IF ( ISINCE<=1 ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'CF time units must contain " since ": '//TRIM(UNITS))
  RETURN
ENDIF
UNIT_NAME=TRIM(ADJUSTL(LOWER_UNITS(1:ISINCE-1)))
REFERENCE_TEXT=TRIM(ADJUSTL(SANITIZE_STRING(UNITS(ISINCE+7:))))

SELECT CASE (TRIM(UNIT_NAME))
CASE ('second','seconds','sec','secs')
  UNIT_MINUTES=1._JPRD/60._JPRD
CASE ('minute','minutes','min','mins')
  UNIT_MINUTES=1._JPRD
CASE ('hour','hours','hr','hrs')
  UNIT_MINUTES=60._JPRD
CASE ('day','days')
  UNIT_MINUTES=1440._JPRD
CASE DEFAULT
  CALL SET_ERROR(IERR,MESSAGE,'unsupported CF time unit: '//TRIM(UNIT_NAME))
  RETURN
END SELECT

CALL NORMALIZE_CALENDAR(CALENDAR,ICAL,NORMALIZED_CALENDAR,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN
CALL PARSE_REFERENCE_DATETIME(REFERENCE_TEXT,ICAL,REFERENCE_MINUTES,IERR,MESSAGE)
END SUBROUTINE PARSE_CF_UNITS
!####################################################################

!####################################################################
SUBROUTINE VALUES_TO_MINUTES(VALUES,UNIT_MINUTES,REFERENCE_MINUTES,MINUTES,IERR,MESSAGE)
REAL(KIND=JPRD), INTENT(IN) :: VALUES(:),UNIT_MINUTES
INTEGER(KIND=JPIB), INTENT(IN) :: REFERENCE_MINUTES
INTEGER(KIND=JPIB), INTENT(OUT) :: MINUTES(:)
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
REAL(KIND=JPRD) :: OFFSET,ROUNDED
INTEGER :: I

IERR=0
MESSAGE=''
DO I=1,SIZE(VALUES)
  OFFSET=VALUES(I)*UNIT_MINUTES
  ROUNDED=ANINT(OFFSET)
  IF ( ABS(OFFSET-ROUNDED)>1.E-7_JPRD ) THEN
    CALL SET_ERROR(IERR,MESSAGE,'CF time value does not align to CaMa-Flood whole-minute time')
    RETURN
  ENDIF
  MINUTES(I)=REFERENCE_MINUTES+INT(NINT(OFFSET,KIND=JPIB),KIND=JPIB)
ENDDO
END SUBROUTINE VALUES_TO_MINUTES
!####################################################################

!####################################################################
SUBROUTINE VALIDATE_TIME_AXIS(AXIS,IERR,MESSAGE)
TYPE(CF_TIME_AXIS), INTENT(INOUT) :: AXIS
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
INTEGER :: I
INTEGER(KIND=JPIB) :: DELTA

IERR=0
MESSAGE=''
IF ( AXIS%NTIME<1 ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'CF time axis must contain at least one record')
  RETURN
ENDIF
IF ( AXIS%NTIME==1 ) THEN
  AXIS%DT_MINUTES=0_JPIB
  IF ( AXIS%HAS_BOUNDS ) THEN
    IF ( AXIS%LOWER_MINUTES(1)>=AXIS%UPPER_MINUTES(1) ) THEN
      CALL SET_ERROR(IERR,MESSAGE,'CF time bounds must be strictly increasing within each record')
      RETURN
    ENDIF
    IF ( AXIS%CENTER_MINUTES(1)<AXIS%LOWER_MINUTES(1) .OR. &
       & AXIS%CENTER_MINUTES(1)>AXIS%UPPER_MINUTES(1) ) THEN
      CALL SET_ERROR(IERR,MESSAGE,'CF time coordinate lies outside its bounds')
      RETURN
    ENDIF
    AXIS%DT_MINUTES=AXIS%UPPER_MINUTES(1)-AXIS%LOWER_MINUTES(1)
  ENDIF
  RETURN
ENDIF
AXIS%DT_MINUTES=AXIS%CENTER_MINUTES(2)-AXIS%CENTER_MINUTES(1)
IF ( AXIS%DT_MINUTES<=0_JPIB ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'CF time axis must be strictly increasing')
  RETURN
ENDIF
DO I=2,AXIS%NTIME
  DELTA=AXIS%CENTER_MINUTES(I)-AXIS%CENTER_MINUTES(I-1)
  IF ( DELTA/=AXIS%DT_MINUTES ) THEN
    CALL SET_ERROR(IERR,MESSAGE,'CF time axis has a gap, overlap, or variable interval')
    RETURN
  ENDIF
ENDDO
IF ( AXIS%HAS_BOUNDS ) THEN
  DO I=1,AXIS%NTIME
    IF ( AXIS%LOWER_MINUTES(I)>=AXIS%UPPER_MINUTES(I) ) THEN
      CALL SET_ERROR(IERR,MESSAGE,'CF time bounds must be strictly increasing within each record')
      RETURN
    ENDIF
    IF ( AXIS%CENTER_MINUTES(I)<AXIS%LOWER_MINUTES(I) .OR. &
       & AXIS%CENTER_MINUTES(I)>AXIS%UPPER_MINUTES(I) ) THEN
      CALL SET_ERROR(IERR,MESSAGE,'CF time coordinate lies outside its bounds')
      RETURN
    ENDIF
    IF ( AXIS%UPPER_MINUTES(I) - AXIS%LOWER_MINUTES(I) /= AXIS%DT_MINUTES ) THEN
      CALL SET_ERROR(IERR,MESSAGE,'CF time-bounds width differs from the time-coordinate interval')
      RETURN
    ENDIF
    IF ( I>1 ) THEN
      IF ( AXIS%LOWER_MINUTES(I)/=AXIS%UPPER_MINUTES(I-1) ) THEN
        CALL SET_ERROR(IERR,MESSAGE,'CF time bounds have a gap or overlap')
        RETURN
      ENDIF
    ENDIF
  ENDDO
ENDIF
END SUBROUTINE VALIDATE_TIME_AXIS
!####################################################################
#endif

#ifdef UseCDF_CMF
!####################################################################
SUBROUTINE CF_READ_TIME_AXIS(NCID,TIME_NAME,AXIS,IERR,MESSAGE)
INTEGER, INTENT(IN) :: NCID
CHARACTER(LEN=*), INTENT(IN) :: TIME_NAME
TYPE(CF_TIME_AXIS), INTENT(OUT) :: AXIS
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
INTEGER :: STATUS,TIME_VARID,NDIMS
INTEGER :: DIMIDS(NF90_MAX_VAR_DIMS),BOUND_DIMIDS(NF90_MAX_VAR_DIMS)
INTEGER :: BOUND_VARID,BOUND_NDIMS,LEN1,LEN2,I
REAL(KIND=JPRD), ALLOCATABLE :: RAW_TIME(:),RAW_BOUND(:,:),LOWER_RAW(:),UPPER_RAW(:)
REAL(KIND=JPRD) :: UNIT_MINUTES
INTEGER(KIND=JPIB) :: REFERENCE_MINUTES
CHARACTER(LEN=CF_STRLEN) :: CALENDAR,BOUND_NAME

IERR=0
MESSAGE=''
CALENDAR='standard'
BOUND_NAME=''

STATUS=NF90_INQ_VARID(NCID,TRIM(TIME_NAME),TIME_VARID)
IF ( STATUS/=NF90_NOERR ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'cannot find NetCDF time coordinate variable: '//TRIM(TIME_NAME))
  RETURN
ENDIF
STATUS=NF90_INQUIRE_VARIABLE(NCID,TIME_VARID,NDIMS=NDIMS,DIMIDS=DIMIDS)
IF ( STATUS/=NF90_NOERR .OR. NDIMS/=1 ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'NetCDF time coordinate must be one-dimensional: '//TRIM(TIME_NAME))
  RETURN
ENDIF
STATUS=NF90_INQUIRE_DIMENSION(NCID,DIMIDS(1),LEN=AXIS%NTIME)
IF ( STATUS/=NF90_NOERR ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'cannot read NetCDF time dimension length')
  RETURN
ENDIF
STATUS=NF90_GET_ATT(NCID,TIME_VARID,'units',AXIS%UNITS)
IF ( STATUS/=NF90_NOERR ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'NetCDF time coordinate is missing required units attribute')
  RETURN
ENDIF
AXIS%UNITS=TRIM(SANITIZE_STRING(AXIS%UNITS))
STATUS=NF90_GET_ATT(NCID,TIME_VARID,'calendar',CALENDAR)
IF ( STATUS/=NF90_NOERR .AND. STATUS/=NF90_ENOTATT ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'cannot read NetCDF time calendar attribute')
  RETURN
ENDIF
CALL PARSE_CF_UNITS(AXIS%UNITS,CALENDAR,UNIT_MINUTES,REFERENCE_MINUTES,AXIS%CALENDAR,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN

ALLOCATE(RAW_TIME(AXIS%NTIME),AXIS%CENTER_MINUTES(AXIS%NTIME))
STATUS=NF90_GET_VAR(NCID,TIME_VARID,RAW_TIME)
IF ( STATUS/=NF90_NOERR ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'cannot read NetCDF time coordinate values')
  RETURN
ENDIF
CALL VALUES_TO_MINUTES(RAW_TIME,UNIT_MINUTES,REFERENCE_MINUTES,AXIS%CENTER_MINUTES,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN

STATUS=NF90_GET_ATT(NCID,TIME_VARID,'bounds',BOUND_NAME)
IF ( STATUS==NF90_NOERR ) THEN
  BOUND_NAME=TRIM(SANITIZE_STRING(BOUND_NAME))
  STATUS=NF90_INQ_VARID(NCID,TRIM(BOUND_NAME),BOUND_VARID)
  IF ( STATUS/=NF90_NOERR ) THEN
    CALL SET_ERROR(IERR,MESSAGE,'time bounds attribute names a missing variable: '//TRIM(BOUND_NAME))
    RETURN
  ENDIF
  STATUS=NF90_INQUIRE_VARIABLE(NCID,BOUND_VARID,NDIMS=BOUND_NDIMS,DIMIDS=BOUND_DIMIDS)
  IF ( STATUS/=NF90_NOERR .OR. BOUND_NDIMS/=2 ) THEN
    CALL SET_ERROR(IERR,MESSAGE,'NetCDF time bounds variable must be two-dimensional')
    RETURN
  ENDIF
  CALL NF90_CHECK_DIMENSION(NCID,BOUND_DIMIDS(1),LEN1,IERR,MESSAGE)
  IF ( IERR/=0 ) RETURN
  CALL NF90_CHECK_DIMENSION(NCID,BOUND_DIMIDS(2),LEN2,IERR,MESSAGE)
  IF ( IERR/=0 ) RETURN
  ALLOCATE(RAW_BOUND(LEN1,LEN2),LOWER_RAW(AXIS%NTIME),UPPER_RAW(AXIS%NTIME))
  STATUS=NF90_GET_VAR(NCID,BOUND_VARID,RAW_BOUND)
  IF ( STATUS/=NF90_NOERR ) THEN
    CALL SET_ERROR(IERR,MESSAGE,'cannot read NetCDF time bounds values')
    RETURN
  ENDIF
  IF ( LEN1==2 .AND. LEN2==AXIS%NTIME ) THEN
    LOWER_RAW=RAW_BOUND(1,:)
    UPPER_RAW=RAW_BOUND(2,:)
  ELSEIF ( LEN1==AXIS%NTIME .AND. LEN2==2 ) THEN
    DO I=1,AXIS%NTIME
      LOWER_RAW(I)=RAW_BOUND(I,1)
      UPPER_RAW(I)=RAW_BOUND(I,2)
    ENDDO
  ELSE
    CALL SET_ERROR(IERR,MESSAGE,'NetCDF time bounds dimensions must be time x 2')
    RETURN
  ENDIF
  AXIS%HAS_BOUNDS=.TRUE.
  ALLOCATE(AXIS%LOWER_MINUTES(AXIS%NTIME),AXIS%UPPER_MINUTES(AXIS%NTIME))
  CALL VALUES_TO_MINUTES(LOWER_RAW,UNIT_MINUTES,REFERENCE_MINUTES,AXIS%LOWER_MINUTES,IERR,MESSAGE)
  IF ( IERR/=0 ) RETURN
  CALL VALUES_TO_MINUTES(UPPER_RAW,UNIT_MINUTES,REFERENCE_MINUTES,AXIS%UPPER_MINUTES,IERR,MESSAGE)
  IF ( IERR/=0 ) RETURN
ELSEIF ( STATUS/=NF90_ENOTATT ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'cannot read NetCDF time bounds attribute')
  RETURN
ENDIF

CALL VALIDATE_TIME_AXIS(AXIS,IERR,MESSAGE)
END SUBROUTINE CF_READ_TIME_AXIS
!####################################################################

!####################################################################
SUBROUTINE NF90_CHECK_DIMENSION(NCID,DIMID,LENGTH,IERR,MESSAGE)
INTEGER, INTENT(IN) :: NCID,DIMID
INTEGER, INTENT(OUT) :: LENGTH
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
INTEGER :: STATUS

IERR=0
MESSAGE=''
STATUS=NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=LENGTH)
IF ( STATUS/=NF90_NOERR ) CALL SET_ERROR(IERR,MESSAGE,'cannot inspect NetCDF time bounds dimension')
END SUBROUTINE NF90_CHECK_DIMENSION
!####################################################################
#endif

!####################################################################
SUBROUTINE CF_FIND_TIME_RECORD(AXIS,YYYYMMDD,HOUR,MINUTE,RECORD,IERR,MESSAGE,REQUIRE_INTERVAL_START)
TYPE(CF_TIME_AXIS), INTENT(IN) :: AXIS
INTEGER(KIND=JPIM), INTENT(IN) :: YYYYMMDD,HOUR,MINUTE
INTEGER(KIND=JPIM), INTENT(OUT) :: RECORD
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
LOGICAL, OPTIONAL, INTENT(IN) :: REQUIRE_INTERVAL_START
INTEGER(KIND=JPIB) :: TARGET
INTEGER :: I
LOGICAL :: REQUIRE_START

RECORD=0
REQUIRE_START=.FALSE.
IF ( PRESENT(REQUIRE_INTERVAL_START) ) REQUIRE_START=REQUIRE_INTERVAL_START
CALL CF_DATETIME_TO_MINUTES(AXIS%CALENDAR,YYYYMMDD,HOUR,MINUTE,TARGET,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN
IF ( AXIS%HAS_BOUNDS ) THEN
  ! Prefer the lower edge when it is also the previous record's coordinate
  ! or upper edge. End-stamped averages then select the interval beginning
  ! at the simulation start rather than the interval that has just ended.
  DO I=1,AXIS%NTIME
    IF ( TARGET==AXIS%LOWER_MINUTES(I) ) THEN
      RECORD=I
      RETURN
    ENDIF
  ENDDO
  ! A coordinate value is also a valid update anchor for centered data whose
  ! bounds do not start at the model start hour.
  DO I=1,AXIS%NTIME
    IF ( TARGET==AXIS%CENTER_MINUTES(I) ) THEN
      RECORD=I
      RETURN
    ENDIF
  ENDDO
  DO I=1,AXIS%NTIME
    IF ( TARGET>=AXIS%LOWER_MINUTES(I) .AND. TARGET<AXIS%UPPER_MINUTES(I) ) THEN
      IF ( REQUIRE_START .AND. TARGET/=AXIS%LOWER_MINUTES(I) ) THEN
        CALL SET_ERROR(IERR,MESSAGE, &
                     &'simulation start lies inside a time bound; start at its coordinate or lower edge')
        RETURN
      ENDIF
      RECORD=I
      RETURN
    ENDIF
  ENDDO
ELSE
  DO I=1,AXIS%NTIME
    IF ( TARGET==AXIS%CENTER_MINUTES(I) ) THEN
      RECORD=I
      RETURN
    ENDIF
  ENDDO
ENDIF
CALL SET_ERROR(IERR,MESSAGE,'simulation start time does not match any NetCDF time record')
END SUBROUTINE CF_FIND_TIME_RECORD
!####################################################################

#ifdef UseCDF_CMF
!####################################################################
SUBROUTINE CF_RESOLVE_TIME_RECORD(NCID,TIME_NAME,YYYYMMDD,HOUR,MINUTE,LLEAPYR, &
                                & EXPECTED_INTERVAL_SECONDS,EXPECTED_NTIME,AXIS,RECORD,IERR,MESSAGE)
INTEGER, INTENT(IN) :: NCID
CHARACTER(LEN=*), INTENT(IN) :: TIME_NAME
INTEGER(KIND=JPIM), INTENT(IN) :: YYYYMMDD,HOUR,MINUTE,EXPECTED_INTERVAL_SECONDS,EXPECTED_NTIME
LOGICAL, INTENT(IN) :: LLEAPYR
TYPE(CF_TIME_AXIS), INTENT(OUT) :: AXIS
INTEGER(KIND=JPIM), INTENT(OUT) :: RECORD,IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
LOGICAL :: CALENDAR_OK

CALL CF_READ_TIME_AXIS(NCID,TIME_NAME,AXIS,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN
IF ( AXIS%NTIME/=EXPECTED_NTIME ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'NetCDF time coordinate length differs from its dimension')
  RETURN
ENDIF
IF ( AXIS%DT_MINUTES>0_JPIB .AND. &
   & AXIS%DT_MINUTES*60_JPIB/=INT(EXPECTED_INTERVAL_SECONDS,KIND=JPIB) ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'configured input interval differs from the NetCDF CF time interval')
  RETURN
ENDIF
CALENDAR_OK=CF_CALENDAR_MATCHES_LLEAPYR(AXIS%CALENDAR,LLEAPYR,IERR,MESSAGE)
IF ( IERR/=0 ) RETURN
IF ( .NOT.CALENDAR_OK ) THEN
  CALL SET_ERROR(IERR,MESSAGE,'NetCDF calendar and LLEAPYR are inconsistent')
  RETURN
ENDIF
CALL CF_FIND_TIME_RECORD(AXIS,YYYYMMDD,HOUR,MINUTE,RECORD,IERR,MESSAGE,.TRUE.)
END SUBROUTINE CF_RESOLVE_TIME_RECORD
!####################################################################
#endif

!####################################################################
LOGICAL FUNCTION CF_CALENDAR_USES_LEAP_DAY(CALENDAR,IERR,MESSAGE)
CHARACTER(LEN=*), INTENT(IN) :: CALENDAR
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
INTEGER :: ICAL
CHARACTER(LEN=32) :: NORMALIZED

ICAL=0
CALL NORMALIZE_CALENDAR(CALENDAR,ICAL,NORMALIZED,IERR,MESSAGE)
CF_CALENDAR_USES_LEAP_DAY=(IERR==0 .AND. ICAL==CAL_GREGORIAN)
END FUNCTION CF_CALENDAR_USES_LEAP_DAY
!####################################################################

!####################################################################
LOGICAL FUNCTION CF_CALENDAR_MATCHES_LLEAPYR(CALENDAR,LLEAPYR,IERR,MESSAGE)
CHARACTER(LEN=*), INTENT(IN) :: CALENDAR
LOGICAL, INTENT(IN) :: LLEAPYR
INTEGER(KIND=JPIM), INTENT(OUT) :: IERR
CHARACTER(LEN=*), INTENT(OUT) :: MESSAGE
LOGICAL :: USES_LEAP

USES_LEAP=CF_CALENDAR_USES_LEAP_DAY(CALENDAR,IERR,MESSAGE)
CF_CALENDAR_MATCHES_LLEAPYR=(IERR==0 .AND. USES_LEAP .EQV. LLEAPYR)
END FUNCTION CF_CALENDAR_MATCHES_LLEAPYR
!####################################################################

END MODULE CMF_CF_TIME_MOD
